### ISSUE TITLE
please don't use private interfaces

### ISSUE THREAD

**Issue by asottile** [verhovsky/pyupgrade-docs#3]
pyupgrade only has a subprocess interface, accessing `pyupgrade._main` is not supported and I will break your package

**Comment by verhovsky** [comment]
You told me this before, in #1. Calling a python library through `subprocess` seems ~~kinda crazy~~needlessly verbose...

Are you still okay with not changing the interface in patch versions https://github.com/verhovsky/pyupgrade-docs/pull/1#issuecomment-519730709 ? I pinned `pyupgrade`'s minor version again (to 2.10.* https://github.com/verhovsky/pyupgrade-docs/commit/516b5bbe00d11696db9e8b0845fbcaf8d85a09c4 ).

I hope you'll change your mind some day. And like I said before, if you find this package abhorrent, I can just delete it.

**Comment by asottile** [comment]
even patch versions may change, there's zero guarantees on things which are intentionally not public

**Comment by verhovsky** [comment]
Makes sense. I pinned the minor version. https://github.com/verhovsky/pyupgrade-docs/commit/ac5643fbf450100dc5908ad74c8feebed7d489b4

**Comment by verhovsky** [comment]
@asottile please tell me what you want.

**Comment by asottile** [comment]
if you want to integrate with pyupgrade, I'd recommend calling it as a subprocess
