### ISSUE TITLE
original LICENSE must be maintained

### ISSUE THREAD

**Issue by asottile** [verhovsky/pyupgrade-docs#4]
MIT is permissive but it requires preserving the original copyright and LICENSE: https://github.com/verhovsky/pyupgrade-docs/commit/ef520e8a38616429342ea8a501de48537e40d4ae#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R1

**Comment by verhovsky** [comment]
done and released as v0.2.3

https://github.com/verhovsky/pyupgrade-docs/commit/131f38349ca15e4d1130c41b7ba611f260efccde
